export const valuesPrint = {
  nombreIesEst: 'LORETO',
  departamento: 'LORETO',
  provincia: 'ALTO AMAZONAS',
  distrito: 'YURIMAGUAS',
  centroPoblado: 'YURIMAGUAS',
  cursos: [
    { id: 1, nombre: 'Realidad Nacional e Internacional' },
    { id: 2, nombre: 'Gestión de Proyectos' },
    { id: 3, nombre: 'Finanzas Corporativas' },
    { id: 4, nombre: 'Marketing Digital' },
    { id: 5, nombre: 'Desarrollo de Software' },
    { id: 6, nombre: 'Inteligencia Artificial' },
    { id: 7, nombre: 'Recursos Humanos' },
    { id: 8, nombre: 'Innovación y Emprendimiento' },
    { id: 9, nombre: 'Logística y Cadena de Suministro' },
    { id: 10, nombre: 'Negociación y Resolución de Conflictos' },
    { id: 11, nombre: 'Economía Internacional' },
    { id: 12, nombre: 'Derecho Corporativo' },
  ],
  alumnos: [
    {
      id: 1,
      dni: '12345678',
      nombre: 'Juan Perez',
      sexo: 'M',
      edad: '20',
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: false,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos',
    },
    {
      id: 2,
      dni: '87654321',
      nombre: 'Maria Lopez',
      sexo: 'F',
      edad: '22',
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: false,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: false,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      id: 3,
      dni: '33345678',
      nombre: 'Diego Francisco',
      sexo: 'M',
      edad: '25',
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: true,
      curso_3: true,
      curso_4: false,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: false,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      id: 4,
      dni: '91654321',
      nombre: 'Sofia Lopez',
      sexo: 'F',
      edad: '21',
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: false,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: false,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      id: 5,
      dni: '44556677',
      nombre: 'Carlos Martinez',
      sexo: 'M',
      edad: '23',
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      id: 6,
      dni: '55443322',
      nombre: 'Ana Torres',
      sexo: 'F',
      edad: '24',
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '33345678',
      nombre: 'Diego Francisco',
      sexo: 'M',
      edad: 25,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: true,
      curso_3: true,
      curso_4: false,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: false,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '91654321',
      nombre: 'Sofia Lopez',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: false,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: false,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '44556677',
      nombre: 'Carlos Martinez',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '55443322',
      nombre: 'Ana Torres',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '66778899',
      nombre: 'Luis Gomez',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '77889900',
      nombre: 'Laura Sanchez',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '88990011',
      nombre: 'Pedro Ramirez',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '99001122',
      nombre: 'Marta Diaz',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '11223344',
      nombre: 'Jorge Herrera',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '22334455',
      nombre: 'Elena Ruiz',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '33445566',
      nombre: 'Ricardo Morales',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '44556688',
      nombre: 'Patricia Fernandez',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '55667799',
      nombre: 'Fernando Castillo',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '66778800',
      nombre: 'Gabriela Ortega',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '77889911',
      nombre: 'Hector Vargas',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '88990022',
      nombre: 'Isabel Mendoza',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '99001133',
      nombre: 'Julio Rojas',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '11223355',
      nombre: 'Karla Jimenez',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '22334466',
      nombre: 'Luis Alvarez',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '33445577',
      nombre: 'Monica Flores',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '44556699',
      nombre: 'Oscar Gutierrez',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '11223355',
      nombre: 'Karla Jimenez',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '22334466',
      nombre: 'Luis Alvarez',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '33445577',
      nombre: 'Monica Flores',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '44556699',
      nombre: 'Oscar Gutierrez',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '11223355',
      nombre: 'Karla Jimenez',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '22334466',
      nombre: 'Luis Alvarez',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '33445577',
      nombre: 'Monica Flores',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '44556699',
      nombre: 'Oscar Gutierrez',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '11223355',
      nombre: 'Karla Jimenez',
      sexo: 'F',
      edad: 21,
      personaDiscapacidad: 'SI',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Excelente rendimiento',
    },
    {
      dni: '22334466',
      nombre: 'Luis Alvarez',
      sexo: 'M',
      edad: 23,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Aprobó todos los cursos con honores',
    },
    {
      dni: '33445577',
      nombre: 'Monica Flores',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '44556699',
      nombre: 'Oscar Gutierrez',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '33445577',
      nombre: 'Monica Flores',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '44556699',
      nombre: 'Oscar Gutierrez',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
    {
      dni: '33445577',
      nombre: 'Monica Flores',
      sexo: 'F',
      edad: 24,
      personaDiscapacidad: 'NO',
      curso_1: false,
      curso_2: false,
      curso_3: true,
      curso_4: true,
      curso_5: true,
      curso_6: false,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: false,
      curso_12: true,
      observaciones: 'Necesita mejorar en algunos cursos',
    },
    {
      dni: '44556699',
      nombre: 'Oscar Gutierrez',
      sexo: 'M',
      edad: 22,
      personaDiscapacidad: 'NO',
      curso_1: true,
      curso_2: true,
      curso_3: true,
      curso_4: true,
      curso_5: false,
      curso_6: true,
      curso_7: true,
      curso_8: true,
      curso_9: true,
      curso_10: true,
      curso_11: true,
      curso_12: true,
      observaciones: 'Buen desempeño en general',
    },
  ],
};
